### ISSUE TITLE
ToolTipDemo Sample

### ISSUE THREAD

**Issue by Cyril325** [JonathanGiles/fx-ui-controls#12]
Since java 9 there is an API to control delay before showing. I suppose in my sample it's java 8.

Do you plan java 9 and later demo ? Should I improve my demo to show how to uninstall tooltip ?

First try https://github.com/JonathanGiles/fx-ui-controls/pull/13

**Comment by JonathanGiles** [comment]
Hey - yes, this content can target up to Java 11 APIs, so please do that! Thanks so much :-)

**Comment by Cyril325** [comment]
Tooltip demo improved to show how to control new java 9 api.
