### ISSUE TITLE
DialogsDemo Sample

### ISSUE THREAD

**Issue by AlmasB** [JonathanGiles/fx-ui-controls#3]

**Comment by JonathanGiles** [comment]
A good starting point for a demo is the code I wrote in JavaFX here: 
https://github.com/teamfx/openjfx-9-dev-rt/blob/master/apps/toys/Hello/src/main/java/hello/HelloDialogs.java

A simplified version of this would be a great start...

**Comment by AlmasB** [comment]
got it, thanks

**Comment by AlmasB** [comment]
Let me know if this is sufficient or a richer example is needed. Otherwise this can be closed

**Comment by JonathanGiles** [comment]
A few small tweaks would be good. For example - make the VBox a little nicer (maybe have all buttons be same width and definitely add 5px of vgap between each element). I can do this though.

More important I would say is to add a small amount of text in each dialog to demonstrate what that does.

Finally, maybe consider writing a Dialog that uses a custom resultConverter (again, HelloDialogs can help here). For example, have a UsernamePassword class and a dialog that asks for a username and password.

**Comment by JonathanGiles** [comment]
Another thing to demonstrate is correct use of the blocking dialog API - that is, calling `showAndWait()` rather than `show()`, and actually getting the return value and printing it to the console.

**Comment by AlmasB** [comment]
- [X] VBox: same width buttons, 5px spacing
- [X] Text in each dialog for demo
- [X] Custom result converter, UsernamePassword
- [X] `showAndWait()`
